# Generated by Django 2.2.3 on 2019-08-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_heroinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='bread',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
